name: tejas
favicon: null
layout_spectrum: 0.5711806402541697
typography_spectrum: 0.17795884958468378
title: 'An Ashtanga Yoga School In Houston,TX'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-119127-3
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.5595491717103869
  lightness: 0.551460082642734
  saturation: 0.8449758016504347
  rhythmicContrast: 0.97349524917081
purpose: []
