name: Tejas Yoga
favicon: null
layout_spectrum: 0.90592
typography_spectrum: 0.65506
title: 'An Ashtanga Yoga School In Houston,TX'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-119127-3
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f8b1b7'
    - '#0e0603'
    - '#a47b69'
    - '#51464a'
    - '#c04f2d'
  brandStrength: 0.5595491717103869
  lightness: 0.551460082642734
  saturation: 0.8449758016504347
  rhythmicContrast: 0.75
purpose: []
