name: Tejas Yoga
favicon: null
layout_spectrum: 0.5711806402541697
typography_spectrum: 0.65506
title: 'An Ashtanga Yoga School In Houston,TX'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-119127-3
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#081118'
    - '#6a4a3b'
    - '#b1d0d2'
    - '#94a0a9'
  brandStrength: 0.5595491717103869
  lightness: 0.551460082642734
  saturation: 0.8449758016504347
  rhythmicContrast: 0.75
purpose: []
